### ISSUE TITLE
Implement a Fourth Workshop Session

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/ruby-for-archivesspace#25]
This should follow the homework assignment from the third workshop session:

- Pick an endpoint which interests you (e. g. one for retrieving Archival Objects within a Collection, Agents of a Specific Type, etc.)
- Get them out as an `Array`
- Iterate over this `Array`
- Pick a set of fields, and please pick two or more fields, and print these to the `STDOUT` using `puts`
  - Preferably this should use string interpolation (https://www.rubyguides.com/2019/07/ruby-string-concatenation/) for the printed output

**Comment by regineheberlein** [comment]
conducted 3/29 via Zoom
